"""Tests for Text-to-Speech synthesis and WAV generation."""

import wave
import io
import pytest
from skeleton.audio.config import AudioConfig
from skeleton.audio.tts import MockTTSClient, OpenAITTSClient


@pytest.mark.asyncio
async def test_mock_tts_generates_valid_wav():
    mock = MockTTSClient(sample_rate=24000)
    audio = await mock.synthesize("Greetings mortal, I am only bones.")
    assert len(audio) > 1000

    # Validate that the generated bytes form a genuine, valid 16-bit PCM WAV file
    with wave.open(io.BytesIO(audio), "rb") as wav_file:
        assert wav_file.getnchannels() == 1
        assert wav_file.getsampwidth() == 2
        assert wav_file.getframerate() == 24000
        assert wav_file.getnframes() > 0


@pytest.mark.asyncio
async def test_tts_empty_string_rejected():
    mock = MockTTSClient()
    with pytest.raises(ValueError, match="Cannot synthesize empty text"):
        await mock.synthesize("   ")
