"""FastAPI audio service exposing /audio_in and /audio_out endpoints."""

import base64
import json
import time
from contextlib import asynccontextmanager
from typing import Any, Dict, List, Literal, Optional
from fastapi import FastAPI, File, HTTPException, Query, Response, UploadFile, status
from pydantic import BaseModel, Field
from sse_starlette.sse import EventSourceResponse

from skeleton.audio.config import AudioConfig
from skeleton.audio.mouth_sync import MouthSyncFrame
from skeleton.audio.pipeline import AudioChunkResponse, AudioDialogueResponse, SkeletonAudioPipeline


class HealthResponse(BaseModel):
    """Service health and loaded model metadata."""

    status: str = "ok"
    gemini_model: str
    tts_model: str
    tts_voice: str
    sample_rate: int
    mouth_fps: int
    prerecorded_sounds_count: int = 0


class PreRecordedSoundModel(BaseModel):
    """Metadata summary of a pre-recorded sound clip."""

    sound_id: str
    category: str
    text: str
    duration_s: float
    mouth_frames_count: int


class MouthSyncFrameModel(BaseModel):
    """Jaw angle tracking frame for physical skull servo synchronization."""

    timestamp_ms: float = Field(..., description="Timestamp in milliseconds from start of utterance.")
    jaw_angle_deg: float = Field(..., description="Target servo jaw angle in degrees (0.0 to max).")
    normalized_open: float = Field(..., description="Normalized jaw-opening proportion (0.0 to 1.0).")


class AudioInResponse(BaseModel):
    """Response returned by /audio_in after processing user microphone speech."""

    user_transcript: str = Field(..., description="Speech transcribed from audio via Whisper.")
    skeleton_response: str = Field(..., description="Snarky skeleton dialogue generated by Gemini.")
    audio_base64: str = Field(..., description="Synthesized deep male WAV audio encoded in base64.")
    mouth_frames: List[MouthSyncFrameModel] = Field(..., description="30Hz jaw-sync frame trajectory.")
    total_latency_ms: float = Field(..., description="Roundtrip processing time in milliseconds.")
    time_to_first_audio_ms: Optional[float] = Field(
        default=None,
        description="Time to first voice audio chunk in milliseconds.",
    )


class AudioChunkStreamModel(BaseModel):
    """Payload model for streamed Server-Sent Events voice chunks."""

    event_type: Literal["transcript", "chunk", "done", "error"]
    chunk_index: Optional[int] = None
    is_final: Optional[bool] = None
    text: Optional[str] = None
    audio_base64: Optional[str] = None
    mouth_frames: Optional[List[MouthSyncFrameModel]] = None
    latency_ms: Optional[float] = None
    cumulative_duration_s: Optional[float] = None


class AudioOutRequest(BaseModel):
    """Request payload for /audio_out text-to-speech synthesis."""

    text: str = Field(..., min_length=1, description="Skeleton dialogue text to synthesize.")
    voice: Optional[str] = Field("onyx", description="OpenAI voice profile ('onyx' is the deep male voice).")
    speed: Optional[float] = Field(0.90, ge=0.25, le=4.0, description="Speech playback rate.")
    format: Optional[Literal["json", "binary"]] = Field(
        "json",
        description="Response format: 'json' (with base64 audio and mouth frames) or 'binary' (raw audio/wav).",
    )


class AudioOutResponse(BaseModel):
    """Structured response returned by /audio_out when format='json'."""

    text: str = Field(..., description="Synthesized text.")
    audio_base64: str = Field(..., description="Synthesized WAV audio bytes in base64.")
    mouth_frames: List[MouthSyncFrameModel] = Field(..., description="30Hz synchronized jaw servo trajectory.")
    latency_ms: float = Field(..., description="Synthesis and envelope extraction turnaround time in ms.")


def _frames_to_models(frames: List[MouthSyncFrame]) -> List[MouthSyncFrameModel]:
    return [
        MouthSyncFrameModel(
            timestamp_ms=f.timestamp_ms,
            jaw_angle_deg=f.jaw_angle_deg,
            normalized_open=f.normalized_open,
        )
        for f in frames
    ]


def create_app(custom_pipeline: Optional[SkeletonAudioPipeline] = None) -> FastAPI:
    """Creates and configures the FastAPI application instance."""

    pipeline_instance = custom_pipeline or SkeletonAudioPipeline()

    @asynccontextmanager
    async def lifespan(app: FastAPI):
        if not hasattr(app.state, "pipeline") or app.state.pipeline is None:
            app.state.pipeline = pipeline_instance
        yield
        if hasattr(app.state, "pipeline") and app.state.pipeline is not None:
            await app.state.pipeline.close()

    app = FastAPI(
        title="Skeleton Animatronic Audio API",
        description="FastAPI service exposing /audio_in (speech-to-dialogue-to-voice) and /audio_out (deep male TTS & mouth-sync).",
        version="1.0.0",
        lifespan=lifespan,
    )
    app.state.pipeline = pipeline_instance

    @app.get("/health", response_model=HealthResponse)
    async def health_check() -> HealthResponse:
        pipeline: SkeletonAudioPipeline = app.state.pipeline
        model_name = getattr(pipeline.orchestrator.config, "model", "unknown")
        return HealthResponse(
            status="ok",
            gemini_model=model_name,
            tts_model=pipeline.config.tts_model,
            tts_voice=pipeline.config.tts_voice,
            sample_rate=pipeline.config.sample_rate,
            mouth_fps=pipeline.config.mouth_fps,
            prerecorded_sounds_count=len(pipeline.sound_bank.sounds),
        )

    @app.get("/sounds", response_model=List[PreRecordedSoundModel])
    async def list_sounds(category: Optional[str] = Query(None, description="Optional category filter")) -> List[PreRecordedSoundModel]:
        """Lists available pre-recorded sounds, optionally filtered by category."""
        pipeline: SkeletonAudioPipeline = app.state.pipeline
        sounds = (
            pipeline.sound_bank.get_by_category(category)
            if category
            else list(pipeline.sound_bank.sounds.values())
        )
        return [
            PreRecordedSoundModel(
                sound_id=s.sound_id,
                category=s.category.value if hasattr(s.category, "value") else str(s.category),
                text=s.text,
                duration_s=s.duration_s,
                mouth_frames_count=len(s.mouth_frames),
            )
            for s in sounds
        ]

    @app.post("/play_sound/{sound_id}")
    async def play_prerecorded_sound(
        sound_id: str,
        format: Optional[Literal["json", "binary"]] = Query("json", description="Response format"),
    ) -> Any:
        """Retrieves and returns pre-recorded audio and cached mouth trajectory instantly."""
        pipeline: SkeletonAudioPipeline = app.state.pipeline
        sound = pipeline.sound_bank.get(sound_id)
        if sound is None:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Pre-recorded sound '{sound_id}' not found.",
            )

        if format == "binary":
            return Response(content=sound.audio_bytes, media_type="audio/wav")

        return AudioOutResponse(
            text=sound.text,
            audio_base64=base64.b64encode(sound.audio_bytes).decode("ascii"),
            mouth_frames=_frames_to_models(sound.mouth_frames),
            latency_ms=0.0,
        )

    @app.post("/audio_in", response_model=AudioInResponse)
    async def audio_in(file: UploadFile = File(...)) -> AudioInResponse:
        """Processes incoming user audio recording through Whisper STT, Gemini dialogue, and Onyx TTS."""
        if not file.filename:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Uploaded file must have a valid filename.",
            )

        raw_bytes = await file.read()
        if len(raw_bytes) < 100:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"Audio payload too small ({len(raw_bytes)} bytes); minimum 100 bytes required.",
            )

        pipeline: SkeletonAudioPipeline = app.state.pipeline
        try:
            resp: AudioDialogueResponse = await pipeline.process_audio_turn(
                audio_bytes=raw_bytes,
                filename=file.filename,
            )
        except Exception as exc:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail=f"Audio pipeline processing failed: {exc}",
            ) from exc

        return AudioInResponse(
            user_transcript=resp.user_transcript,
            skeleton_response=resp.skeleton_response,
            audio_base64=base64.b64encode(resp.audio_bytes).decode("ascii"),
            mouth_frames=_frames_to_models(resp.mouth_frames),
            total_latency_ms=resp.total_latency_ms,
            time_to_first_audio_ms=resp.time_to_first_audio_ms,
        )

    @app.post("/audio_in_stream")
    async def audio_in_stream(file: UploadFile = File(...)) -> EventSourceResponse:
        """Processes microphone audio and streams synthesized voice chunks via SSE in real time.

        Drastically reduces voice response latency by sending each synthesized sentence clause
        immediately as generated, alongside real-time 30Hz jaw servo trajectory frames.
        """
        if not file.filename:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Uploaded file must have a valid filename.",
            )

        raw_bytes = await file.read()
        if len(raw_bytes) < 100:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"Audio payload too small ({len(raw_bytes)} bytes); minimum 100 bytes required.",
            )

        pipeline: SkeletonAudioPipeline = app.state.pipeline

        async def event_generator():
            t0 = time.perf_counter()
            try:
                # 1. Transcribe audio input using Whisper
                transcript = await pipeline.stt_client.transcribe(raw_bytes, filename=file.filename)
                yield {
                    "event": "transcript",
                    "data": json.dumps({"transcript": transcript}),
                }

                # 2. Stream dialogue generation, TTS synthesis, and jaw sync frames
                async for chunk in pipeline.process_text_stream(transcript, t0=t0):
                    data = {
                        "chunk_index": chunk.chunk_index,
                        "is_final": chunk.is_final,
                        "text": chunk.text,
                        "audio_base64": base64.b64encode(chunk.audio_bytes).decode("ascii"),
                        "mouth_frames": [m.model_dump() for m in _frames_to_models(chunk.mouth_frames)],
                        "latency_ms": chunk.latency_ms,
                        "cumulative_duration_s": chunk.cumulative_duration_s,
                    }
                    yield {
                        "event": "chunk",
                        "data": json.dumps(data),
                    }

                total_ms = (time.perf_counter() - t0) * 1000.0
                yield {
                    "event": "done",
                    "data": json.dumps({"total_latency_ms": round(total_ms, 2)}),
                }

            except Exception as exc:
                yield {
                    "event": "error",
                    "data": json.dumps({"error": str(exc)}),
                }

        return EventSourceResponse(event_generator())

    @app.post("/audio_out")
    async def audio_out(req: AudioOutRequest) -> Any:
        """Synthesizes dialogue text into the deep male skeleton voice with mouth sync."""
        clean_text = req.text.strip()
        if not clean_text:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Text to synthesize cannot be empty.",
            )

        pipeline: SkeletonAudioPipeline = app.state.pipeline
        t0 = time.perf_counter()

        try:
            wav_bytes = await pipeline.tts_client.synthesize(
                clean_text,
                voice=req.voice or pipeline.config.tts_voice,
                speed=req.speed or pipeline.config.tts_speed,
                response_format="wav",
            )
        except Exception as exc:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail=f"Speech synthesis failed: {exc}",
            ) from exc

        # Binary format: return raw audio/wav stream directly
        if req.format == "binary":
            return Response(content=wav_bytes, media_type="audio/wav")

        # JSON format: extract mouth sync frames and return structured package
        mouth_frames = pipeline.mouth_sync.extract_jaw_trajectory(wav_bytes)
        elapsed_ms = (time.perf_counter() - t0) * 1000.0

        return AudioOutResponse(
            text=clean_text,
            audio_base64=base64.b64encode(wav_bytes).decode("ascii"),
            mouth_frames=_frames_to_models(mouth_frames),
            latency_ms=round(elapsed_ms, 2),
        )

    return app


# Default application instance for Uvicorn
app = create_app()
